### PR TITLE
Applying custom rules to its own code

### PR DESCRIPTION
**Pull request by gaelcolas**
This PR brings it up to date with current version found in `DscResource.Tests`.

Because it uses its own module to apply, it will only work after the module is built with:
`build.ps1 -tasks build` (and `-ResolveDependency` if it's the first time)

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dscresource.analyzerrules/3)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Will review once the tests are passing :grin:

**Comment by gaelcolas** [comment]
the `-Skip:(![bool]$IsWindows)` for DSC tests worked.
Tests are passing now @PlagueHO :)

**Comment by johlju** [comment]
> We generally do like to stick as closely to the style guidelines as possible, even in the tests because it just makes it easier to adhere to the guidelines

I agree with @PlagueHO here. See my comment in the thread in Slack as well.

**Comment by gaelcolas** [comment]
As discussed with @PlagueHO in slack, this:
```
$ProjectName = (Get-ChildItem -Path $ProjectPath\*\*.psd1).Where({
        ($_.Directory.Name -match 'source|src' -or $_.Directory.Name -eq $_.BaseName) -and
$(try { Test-ModuleManifest -Path $_.FullName -ErrorAction Stop } catch { $false } )
    }).BaseName
```
Is better than statically naming:
`$Script:ModuleName = 'modulename'`

So I'll update to this (after making sure it works).
Priority here is to keep it concise, and avoid having a dependency _just for that_.

**Pull request merged**
