### PR TITLE
Update repo files

### PR DESCRIPTION
**Pull request by dan-hughes**
Align with the other dsccommunity repositories.

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-hughes)

___
*[`.github/PULL_REQUEST_TEMPLATE.md` line 44 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19#-O8XILZkDMMweXLOHWXJ:-O8XILZkDMMweXLOHWXK:btkowez) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/871c67cf5b14cb9c2d38e7c42995e2a259bef6a5/.github/PULL_REQUEST_TEMPLATE.md#L44)):*
> ```Markdown
>       Entry should say what was changed and how that affects users (if applicable), and
>       reference the issue being resolved (if applicable).
> - [ ] Resource documentation added/updated in README.md.
> ```

There are no resources in this module so we probably should use the template from: https://github.com/dsccommunity/DscResource.Common/blob/main/.github/PULL_REQUEST_TEMPLATE.md
___
*[`.github/ISSUE_TEMPLATE/03_problem_with_module.yml` line 96 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19#-O8XIc8NBTgyOouQEOH_:-O8XIc8NBTgyOouQEOHa:b56kr10) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/871c67cf5b14cb9c2d38e7c42995e2a259bef6a5/.github/ISSUE_TEMPLATE/03_problem_with_module.yml#L96)):*
> ```YAML
>         Please provide the version of the DscConfig.Demo module that was used. _Will be automatically formatted as plain text._
> 
>         To help with this information, please run this command: `Get-Module -Name 'DscConfig.Demo' -ListAvailable | ft Name,Version,Path`
> ```

Might change the name here



_Suggestion:_
```YAML
'DscResource.AnalyzerRules'
```

**Review by dan-hughes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[`.github/PULL_REQUEST_TEMPLATE.md` line 44 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19#-O8XILZkDMMweXLOHWXJ:-O8XKnWn3Ahq57chBqKX:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/871c67cf5b14cb9c2d38e7c42995e2a259bef6a5/.github/PULL_REQUEST_TEMPLATE.md#L44)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

There are no resources in this module so we probably should use the template from: https://github.com/dsccommunity/DscResource.Common/blob/main/.github/PULL_REQUEST_TEMPLATE.md
</blockquote></details>

Done.
___
*[`.github/ISSUE_TEMPLATE/03_problem_with_module.yml` line 96 at r2](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19#-O8XIc8NBTgyOouQEOH_:-O8XKpSp9k--6SHrOlUf:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/871c67cf5b14cb9c2d38e7c42995e2a259bef6a5/.github/ISSUE_TEMPLATE/03_problem_with_module.yml#L96)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Might change the name here
</blockquote></details>

Done.

**Review by johlju — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19)* status: all files reviewed, 1 unresolved discussion (waiting on @dan-hughes)

*[a discussion](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19#-O8XMICkAoz5GtZd_qgA:-O8XMICkAoz5GtZd_qgB:b-d3i26y) (no related file):*
I'm in the process of renaming the default branch, so this need to resolve conflicts in a while.

___

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19)* status: all files reviewed, 2 unresolved discussions (waiting on @dan-hughes)

___
*[`codecov.yml` line 4 at r3](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19#-O8XNfeV62x3CceMYnOC:-O8XNfeV62x3CceMYnOD:br0xuqk) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/1e1c28580fbcbcb702e72f63844724c3597ba344/codecov.yml#L4)):*
> ```YAML
>   require_ci_to_pass: no
>   # master should be the baseline for reporting
>   branch: master
> ```

Change branch name to main



_Suggestion:_
```YAML
main
```

**Comment by dan-hughes** [comment]
@johlju let me know when you're done and I'll merge the changes. I have replaced any references to master in my local branch.

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19)* status: all files reviewed, 3 unresolved discussions (waiting on @dan-hughes)

___
*[`README.md` line 5 at r3](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19#-O8XQDZD5tKDKrda2mOJ:-O8XQDZD5tKDKrda2mOK:bqs0hrt) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/1e1c28580fbcbcb702e72f63844724c3597ba344/README.md#L5)):*
> ```Markdown
> PS Script Analyzer Custom Rules for the DSC Community standards
> 
> [Build Status](https://dev.azure.com/dsccommunity/DscResource.AnalyzerRules/_build/latest?definitionId=2&branchName=master)
> ```

Update to branch main throughout the status "flags"



_Suggestion:_
```Markdown
main
```

**Comment by johlju** [comment]
Rename is done, you good to resolve conflicts in this PR and fix comments 🙂  Thank you!

**Review by dan-hughes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19)* status: 10 of 14 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[`codecov.yml` line 4 at r3](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19#-O8XNfeV62x3CceMYnOC:-O8XUYAh3aCDEhcuxbuy:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/1e1c28580fbcbcb702e72f63844724c3597ba344/codecov.yml#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Change branch name to main
</blockquote></details>

Done.
___
*[`README.md` line 5 at r3](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19#-O8XQDZD5tKDKrda2mOJ:-O8XUZit7cuQIwKo2IQl:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/1e1c28580fbcbcb702e72f63844724c3597ba344/README.md#L5)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Update to branch main throughout the status "flags"
</blockquote></details>

Done.

**Comment by dan-hughes** [comment]
@johlju, all done.

**Review by johlju — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Review by johlju — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/19#-:-O8XWTFJ5NVRrPtHVDlt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Pull request merged**
