### PR TITLE
Add docgenerator and hqrmtests

### PR DESCRIPTION
**Pull request by dan-hughes**
Add generated docs using `DscResource.DocGenerator` and HQRM tests.

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/21)

### CODE REVIEW

**Comment by dan-hughes** [comment]
On hold until the remaining PR's are merged:

- [ ] #17
- [ ] #18 
- [ ] #19 
- [ ] #20

**Comment by johlju** [comment]
You can run with this one now when you have time. 🙂 

>[!NOTE]
>Make sure to rename folder `Source` to `source` (lower-case `s`)

**Comment by dan-hughes** [comment]
Waiting on the following:

- #27

**Comment by dan-hughes** [comment]
@johlju, ready to go.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r3, 45 of 45 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/21#-:-O8elVj31pCR_cMEsSgM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Comment by johlju** [comment]
Awesome work on this entire module! Nice to have this up to speed also! 🙂

**Pull request merged**
