### PR TITLE
Fix Build

### PR DESCRIPTION
**Pull request by dan-hughes**
Update files to allow build to work.

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/14)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
Looks good. Not sure why build fails though.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/14#-:-O81L-AJ5BoSzuI7ovQt:b8zp4qo)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dan-hughes)

**Comment by johlju** [comment]
Ah, the [module manifest points to a specific version](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/da9ab6446c0c6509084193a5ec0a61e0997b1485/Source/DscResource.AnalyzerRules.psd1#L46-L48), but we download a newer in [RequiredModules.psd1](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/master/RequiredModules.psd1). I'm not even sure we need to keep the dependency in the module manifest? If we keep it it should be minimum version, not required version. 🤔

**Comment by johlju** [comment]
I will merge this as soon as the status checks passes.

**Comment by dan-hughes** [comment]
> Ah, the [module manifest points to a specific version](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/da9ab6446c0c6509084193a5ec0a61e0997b1485/Source/DscResource.AnalyzerRules.psd1#L46-L48), but we download a newer in [RequiredModules.psd1](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/master/RequiredModules.psd1). I'm not even sure we need to keep the dependency in the module manifest, but maybe it is good? If we keep it it should be minimum version, not required version. 🤔

I removed PSSA from required modules which then caused a type error. I think adding an import into the prefix may fix but that can go on the todo list.

**Comment by dan-hughes** [comment]
@johlju

**Pull request merged**
