### PR TITLE
Add wiki documentation for usage

### LINKED ISSUE #10: How do I use these?
Is it possible to get some documentation made on how to use these rules? Providing DscResource.AnalyzerRules.psm1 to the customrules path on Invoke-ScriptAnaylzer just throws exceptions

### PR DESCRIPTION
**Pull request by johlju**
#### This Pull Request (PR) fixes the following issues
- Fixes #10 

#### Task list
- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated for all new/changed functions.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See
  [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28)

### CODE REVIEW

**Comment by johlju** [comment]
@dan-hughes if you have time, can you proof read this one?

**Comment by dan-hughes** [comment]
Yes. I will review tomorrow.

**Review by dan-hughes — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28)* status: all files reviewed, 5 unresolved discussions (waiting on @johlju)

___
*[`source/WikiSource/Visual_Studio_Code.md` line 11 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28#-O8iA1BO0-8CQdvFdn-_:-O8iA1BO0-8CQdvFdn-a:bb7r2vr) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/be718414f96ed6f989c3dead5ee99c616b2ca6ec/source/WikiSource/Visual_Studio_Code.md#L11)):*
> ```Markdown
> 
> It also assumed the latest version of PSScriptAnalyzer is installed in a `$PSModulePath`.
> It probably do, but it is not expected to with with the version of PSScriptAnalyzer
> ```

will



_Code quote:_
```Markdown
do
```
___
*[`source/WikiSource/Visual_Studio_Code.md` line 11 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28#-O8iA_bl9SSpKyWv3ZTT:-O8iA_bm3s4JzN8matma:bvkix2p) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/be718414f96ed6f989c3dead5ee99c616b2ca6ec/source/WikiSource/Visual_Studio_Code.md#L11)):*
> ```Markdown
> 
> It also assumed the latest version of PSScriptAnalyzer is installed in a `$PSModulePath`.
> It probably do, but it is not expected to with with the version of PSScriptAnalyzer
> ```

Not required



_Code quote:_
```Markdown
with
```
___
*[`source/WikiSource/Visual_Studio_Code.md` line 55 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28#-O8iBANU38GYashbuOdC:-O8iBANU38GYashbuOdD:b-7m9n48) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/be718414f96ed6f989c3dead5ee99c616b2ca6ec/source/WikiSource/Visual_Studio_Code.md#L55)):*
> ```Markdown
> root of the project.
> 
> If the project need to use several modules with custom rules, see [Custom rules](https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/using-scriptanalyzer?view=ps-modules#custom-rules).
> ```

needs



_Code quote:_
```Markdown
need
```
___
*[`source/WikiSource/Visual_Studio_Code.md` line 58 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28#-O8iBHb5-Bp4g5Hw-tGC:-O8iBHb5-Bp4g5Hw-tGD:b-hkmncz) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/be718414f96ed6f989c3dead5ee99c616b2ca6ec/source/WikiSource/Visual_Studio_Code.md#L58)):*
> ```Markdown
> 
> The important part here is `CustomRulePath` which should point to the relative or
> absolute path to where this module is installed. Below setting assume the project
> ```

The below



_Code quote:_
```Markdown
Below
```
___
*[`source/WikiSource/Visual_Studio_Code.md` line 58 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28#-O8iBRHwBuG4qw6yd0gL:-O8iBRHwBuG4qw6yd0gM:bnw0nfm) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/be718414f96ed6f989c3dead5ee99c616b2ca6ec/source/WikiSource/Visual_Studio_Code.md#L58)):*
> ```Markdown
> 
> The important part here is `CustomRulePath` which should point to the relative or
> absolute path to where this module is installed. Below setting assume the project
> ```

assumes



_Code quote:_
```Markdown
assume
```

**Review by dan-hughes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28)* status: all files reviewed, 5 unresolved discussions (waiting on @johlju)

___
*[`source/WikiSource/Visual_Studio_Code.md` line 58 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28#-O8kLI4NAeLaqAvJXw3h:-O8kLI4NAeLaqAvJXw3i:b-b40mvs) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/be718414f96ed6f989c3dead5ee99c616b2ca6ec/source/WikiSource/Visual_Studio_Code.md#L58)):*
> ```Markdown
> 
> The important part here is `CustomRulePath` which should point to the relative or
> absolute path to where this module is installed. Below setting assume the project
> ```

settings



_Code quote:_
```Markdown
setting
```

**Comment by dan-hughes** [comment]
Ignore the `assume` correction. Use the `settings` correction instead.

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @dan-hughes)

___
*[`source/WikiSource/Visual_Studio_Code.md` line 11 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28#-O8iA1BO0-8CQdvFdn-_:-O8l3W2S7glDKIhcWVyr:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/be718414f96ed6f989c3dead5ee99c616b2ca6ec/source/WikiSource/Visual_Studio_Code.md#L11)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

will
</blockquote></details>

Done.
___
*[`source/WikiSource/Visual_Studio_Code.md` line 11 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28#-O8iA_bl9SSpKyWv3ZTT:-O8l3YKLATls9IIghbWl:b-ldw17x) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/be718414f96ed6f989c3dead5ee99c616b2ca6ec/source/WikiSource/Visual_Studio_Code.md#L11)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

Not required
</blockquote></details>

Done. Not sure this one is correct. Rephrased.
___
*[`source/WikiSource/Visual_Studio_Code.md` line 55 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28#-O8iBANU38GYashbuOdC:-O8l3byX3thSvXKwz1Kk:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/be718414f96ed6f989c3dead5ee99c616b2ca6ec/source/WikiSource/Visual_Studio_Code.md#L55)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

needs
</blockquote></details>

Done.
___
*[`source/WikiSource/Visual_Studio_Code.md` line 58 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28#-O8iBHb5-Bp4g5Hw-tGC:-O8l3e06AggcyF_zKQ2h:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/be718414f96ed6f989c3dead5ee99c616b2ca6ec/source/WikiSource/Visual_Studio_Code.md#L58)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

The below
</blockquote></details>

Done.
___
*[`source/WikiSource/Visual_Studio_Code.md` line 58 at r1](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28#-O8kLI4NAeLaqAvJXw3h:-O8l3f3L1GQgXjHtPDm1:b-896fix) ([raw file](https://github.com/dsccommunity/DscResource.AnalyzerRules/blob/be718414f96ed6f989c3dead5ee99c616b2ca6ec/source/WikiSource/Visual_Studio_Code.md#L58)):*
<details><summary><i>Previously, dan-hughes (Daniel Hughes) wrote…</i></summary><blockquote>

settings
</blockquote></details>

Done.

**Review by dan-hughes — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DscResource.AnalyzerRules/28#-:-O8l4A5ADxqJr_0lT_hC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @johlju)

**Pull request merged**
